joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 120

# Position Controllers ---------------------------------------
stand_cart_position_controller:
  type: effort_controllers/JointPositionController
  joint: stand_cart
  pid: {p: 100, i: 0.01, d: 10}

cart_pole_position_controller:
  type: effort_controllers/JointPositionController
  joint: cart_pole
  pid: {p: 100, i: 0.01, d: 10}


# waist_pendulum_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: waist_pendulum
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# top_pendulum_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: top_pendulum
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# shankL_footL_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: shankL_footL
#   pid: {p: 100.0, i: 0.01, d: 10.0}

# waist_boom_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: waist_boom
#   pid: {p: 100.0, i: 0.01, d: 10.0}


# pivot_boom_position_controller:
#   type: effort_controllers/JointPositionController
#   joint: boom_pivot
#   pid: {p: 100.0, i: 0.01, d: 10.0}
